from django.conf.urls import patterns, include, url
from member import views

urlpatterns = patterns('',
                    url(r'^members$', views.index, name='member.index'),
                    url(r'^members/add$', views.add, name='member.add'),
                    url(r'^members/edit/(\d+)$', views.edit, name='member.edit'),
                    url(r'^members/resetpassword/(\d+)$', views.reset_password, name='member.reset_password'),
                    url(r'^members/matching_list$', views.matching_list, name='member.matching_list'),
                    url(r'^members/matching$', views.matching, name='member.matching'),
                    url(r'^businesscard/(?P<file_name>.+)$', views.get_businesscard, name='member.get_businesscard'),
                    url(r'^companies$', views.companies, name='company.list'),
                    url(r'^companies/add$', views.add_company, name='company.add'),
                    url(r'^companies/edit/(\d+)$', views.edit_company, name='company.edit'),
                    url(r'^companies/remove_file$', views.remove_company_file, name='company.remove_file'),
                    url(r'^companies/remove_logo$', views.remove_company_logo, name='company.remove_logo'),
                    url(r'^companies/remove$', views.remove_company, name='company.remove'),
                    url(r'^companies/autocomplete_search/(.+)$', views.company_autocomplete_search, name='company.autocomplete_search'),
                    url(r'^members/autocomplete_search/(.+)$', views.member_autocomplete_search, name='member.autocomplete_search'),
                    url(r'^members/invite$', views.invite, name='member.invite'),
                    url(r'^members/sendmail$', views.sendmail, name='member.sendmail'),
                    url(r'^messages', views.member_messages, name='member.messages'),
                    url(r'^entryforms$', views.entryforms, name='entryform.list'),
                    url(r'^entryforms/check/(\d+)$', views.entryform_check, name='entryform.check'),
                    url(r'^entryforms/detail/(\d+)$', views.entryform_detail, name='entryform.detail'),
                    url(r'^contacts', views.contact_cvsource, name='member.contact_cvsource'),
                    url(r'^companies/investment_history/remove$', views.remove_company_investment_history, name='company.investment_history_remove'),
                    url(r'^companies/investment_history/edit/(\d+)$', views.edit_company_investment_history, name='company.investment_history_edit'),
                    url(r'^companies/investment_history/add/(\d+)$', views.add_company_investment_history, name='company.investment_history_add'),
                    url(r'^companies/matching/add/(\d+)$', views.add_company_matching, name='company.matching_add'),
                    url(r'^companies/matching/edit/(\d+)$', views.edit_company_matching, name='company.matching_edit'),
                    url(r'^companies/matching/remove$', views.remove_company_matching, name='company.matching_remove'),
                    url(r'^members/matching/add/(\d+)$', views.add_member_matching, name='member.matching_add'),
                    url(r'^members/matching/edit/(\d+)$', views.edit_member_matching, name='member.matching_edit'),
                    url(r'^members/matching/remove$', views.remove_member_matching, name='member.matching_remove'),
                    url(r'^members/tracking/add/(\d+)$', views.add_member_tracking, name='member.tracking_add'),
                    

)
