from django.conf.urls import patterns, include, url

from sales import views

urlpatterns = patterns('',
    url(r'^mydetail/(\d+)/$', views.mydetail, name='sales.mydetail'),
	url(r'^detail/(\d+)/$', views.detail, name='sales.detail'),
    url(r'^pdf/(\d+)/$', views.pdf, name='sales.pdf'),
    url(r'^download_attach/(\d+)/$', views.download_attach, name='sales.download_attach'),
	url(r'^save$', views.save, name='sales.save'),
	url(r'^view_email/(\d+)$', views.view_email, name='sales.view_email'),
    #url(r'^mylist$', views.mylist, {'type': 'release'}, name='sales.mylist'),
	#url(r'^mylist/(?P<id>\d+)/$', views.mylist, {'type': 'release'}, name='sales.mylist'),
    url(r'^mylist$', views.mylist, {'type': 'release'}, name='sales.mylist'),
    #url(r'^mylist/(?P<type>\w+)/(?P<id>\d+)/$', views.mylist, name='sales.mylist'),
	#url(r'^mylist/(?P<id>\d+)/$', views.mylist, {'type': 'all'}, name='sales.mylist'),
    #url(r'^mylist_public', views.mylist, {'type': 'public'}, name='sales.mylist_public'),
	#url(r'^mylist_public/(?P<id>\d+)/$', views.mylist, {'type': 'public'}, name='sales.mylist_public'),
    #url(r'^mylist_private', views.mylist, {'type': 'private'}, name='sales.mylist_private'),
	#url(r'^mylist_private/(?P<id>\d+)/$', views.mylist, {'type': 'private'}, name='sales.mylist_private'),
    url(r'^mylist_draft', views.mylist,{'type': 'draft'},name='sales.mylist_draft'),
    #url(r'^mylist_draft/(?P<id>\d+)/$', views.mylist, {'type': 'draft'}, name='sales.mylist_draft'),
    url(r'^mylist_release', views.mylist,{'type': 'release'},name='sales.mylist_release'),
    url(r'^mylist_expired', views.mylist,{'type': 'expired'},name='sales.mylist_expired'),
    url(r'^mylist_offline', views.mylist,{'type': 'offline'},name='sales.mylist_offline'),
    url(r'^mylist_pending', views.mylist,{'type': 'pending'}, name='sales.mylist_pending'),
    url(r'^mylist_not_approved', views.mylist,{'type': 'not_approved'},name='sales.mylist_not_approved'),
	url(r'^new/(\d+)$', views.new, name='sales.new'),
	url(r'^new$', views.new, name='sales.new'),
    url(r'^search_keyword$', views.search_keyword, name='sales.search_keyword'),
	url(r'^search$', views.search, name='sales.search'),
    url(r'^add$', views.add,{'type':0}, name='sales.add'),
	url(r'^add/(\d+)/$', views.add, name='sales.add'),
	url(r'^edit/(\d+)/$', views.edit, name='sales.edit'),
	url(r'^json_index', views.json_index, name='sales.json_index'),
	#url(r'^json$', views.json, name='sales.json'),
    url(r'^pending', views.pending, name='sales.pending'),
    url(r'^delete', views.delete, name='sales.delete'),
    url(r'^offline', views.offline, name='sales.offline'),
    url(r'^removeFile', views.remove_file, name='sales.removeFile'),
    url(r'^ajax_more$', views.ajax_more, name='sales.ajax_more'),
    #url(r'^save_recommend_company', views.save_recommend_company, name='sales.save_recommend_company'),
	url(r'^one_click', views.one_click, name='sales.one_click'),
	url(r'^upload_file', views.upload_file, name='sales.upload_file'),
	url(r'^json_recommend_count', views.json_recommend_count, name='sales.json_recommend_count'),
	url(r'^json_recommend$', views.json_recommend, name='sales.json_recommend'),
	url(r'^sync_recommond$', views.sync_recommond, name='sales.sync_recommond'),
	url(r'^bankingGenuisSave', views.bankingGenuisSave, name='sales.bankingGenuisSave'),
	url(r'^bankingGenuisExcute', views.bankingGenuisExcute, name='sales.bankingGenuisExcute'),
	url(r'^send_extenal_email$', views.send_extenal_email, name='sales.send_extenal_email'),

)
